name: Release Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the release (existing tag)'
        required: true
        type: string

jobs:
  build-and-release:
    if: github.actor == 'tibagni'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout at TAG
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Jar
        run: ./gradlew shadowJar

      - name: Find JAR output
        id: jar
        run: |
          JAR_PATH=$(find . -name '*.jar' | head -n 1)
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true
          files: ${{ steps.jar.outputs.jar_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
